import { WorkflowPhase } from '@/types';

// ============================================================
// AIICC 五阶段工作流定义（中小学生友好版）
// ============================================================

export const workflowPhases: WorkflowPhase[] = [
  {
    id: 1,
    name: '发现',
    icon: '🔍',
    description: '找到你想解决的问题',
    steps: [
      {
        id: '1-1',
        phase: 1,
        step: 1,
        title: '你想解决什么？',
        description: '说说看，生活中有什么事情让你觉得"要是能变好就好了"？',
        aiRole: 'socrates',
        outputType: 'text',
        promptHint: '引导学员说出想解决的问题，用提问帮助聚焦',
      },
      {
        id: '1-2',
        phase: 1,
        step: 2,
        title: '追根问底 — 连续问"为什么"',
        description: '像侦探一样，连续追问"为什么"，找到问题真正的根因',
        aiRole: 'socrates',
        outputType: 'text',
        promptHint: '用 5Why 方法引导学员逐层深入，不要跳步骤',
      },
      {
        id: '1-3',
        phase: 1,
        step: 3,
        title: '链接联合国目标',
        description: '你关心的问题和联合国 17 个全球目标，哪个有关系？',
        aiRole: 'analyst',
        outputType: 'text',
        promptHint: '帮助学员将问题映射到 SDG 目标，给出匹配理由',
      },
      {
        id: '1-4',
        phase: 1,
        step: 4,
        title: '谁会受影响？',
        description: '谁会因为这个问题而烦恼？描述一下他们的样子',
        aiRole: 'analyst',
        outputType: 'text',
        promptHint: '帮助学员构建用户画像：年龄、场景、痛点、需求',
      },
    ],
  },
  {
    id: 2,
    name: '定义',
    icon: '🎯',
    description: '想清楚你的方案有什么特别',
    steps: [
      {
        id: '2-1',
        phase: 2,
        step: 1,
        title: '你的方案好在哪？',
        description: '你的方案能帮用户解决什么？和别人比有什么不一样？',
        aiRole: 'analyst',
        outputType: 'canvas',
        promptHint: '引导学员完成价值画布：用户痛点→解决方案→价值主张',
      },
      {
        id: '2-2',
        phase: 2,
        step: 2,
        title: '看看别人怎么做',
        description: '别人是怎么解决这个问题的？你的想法和他们有什么不同？',
        aiRole: 'analyst',
        outputType: 'text',
        promptHint: '帮助学员找到 2-3 个竞品或类似方案，分析优劣势',
      },
      {
        id: '2-3',
        phase: 2,
        step: 3,
        title: '最关键的猜测',
        description: '你的方案里，哪一个猜测如果猜错了就全盘皆输？',
        aiRole: 'analyst',
        outputType: 'text',
        promptHint: '帮学员识别 leap-of-faith assumption：区分价值假设和增长假设',
      },
      {
        id: '2-4',
        phase: 2,
        step: 4,
        title: '给你的项目取个名字',
        description: '用一句话说清楚你的项目是做什么的，再给它取个好名字',
        aiRole: 'analyst',
        outputType: 'text',
        promptHint: '帮助学员完成项目命名、简介和目标陈述',
      },
    ],
  },
  {
    id: 3,
    name: '构思',
    icon: '💡',
    description: '天马行空想点子，选出最好的',
    steps: [
      {
        id: '3-1',
        phase: 3,
        step: 1,
        title: '头脑风暴',
        description: '天马行空！想出至少 10 个可能的办法',
        aiRole: 'creative',
        outputType: 'list',
        promptHint: '鼓励发散思维，先不评判，数量优先，至少 10 个',
      },
      {
        id: '3-2',
        phase: 3,
        step: 2,
        title: '选出最好的点子',
        description: '从 10 个创意里选出最棒的 2-3 个',
        aiRole: 'creative',
        outputType: 'text',
        promptHint: '帮学员建立筛选标准：可行性、影响力、创新性',
      },
      {
        id: '3-3',
        phase: 3,
        step: 3,
        title: '把想法变成方案',
        description: '把选中的好点子变成一个具体的方案',
        aiRole: 'creative',
        outputType: 'text',
        promptHint: '引导学员描述方案的核心功能、使用场景、目标用户',
      },
      {
        id: '3-4',
        phase: 3,
        step: 4,
        title: '检查你的创意够不够新',
        description: '你的方案够新吗？和别人比有什么不一样？',
        aiRole: 'reviewer',
        outputType: 'text',
        promptHint: '从新颖性、实用性、社会价值三个维度评估创新性',
      },
    ],
  },
  {
    id: 4,
    name: '原型',
    icon: '🛠️',
    description: '动手做出最简单的版本',
    steps: [
      {
        id: '4-1',
        phase: 4,
        step: 1,
        title: '做个最简单的版本',
        description: '最少要做出什么东西，才能知道你的想法对不对？',
        aiRole: 'architect',
        outputType: 'text',
        promptHint: '帮助学员定义最小可行产品范围，克制地做减法',
      },
      {
        id: '4-2',
        phase: 4,
        step: 2,
        title: '画一画你的方案',
        description: '用纸笔或工具画出你的方案长什么样',
        aiRole: 'architect',
        outputType: 'text',
        promptHint: '引导学员描述产品界面和用户体验流程',
      },
      {
        id: '4-3',
        phase: 4,
        step: 3,
        title: '需要用到什么？',
        description: '做你的方案需要用到什么技术或材料？',
        aiRole: 'architect',
        outputType: 'text',
        promptHint: '帮助学员选择合适的技术栈，考虑学员的实际能力',
      },
      {
        id: '4-4',
        phase: 4,
        step: 4,
        title: '做出来→试一试→学一学',
        description: '做出一个最简单的版本 → 找人试试 → 从反馈中学到东西，决定继续还是换个方向',
        aiRole: 'architect',
        outputType: 'list',
        promptHint: '引导学员设计 BML 循环：定义可操作指标，预设 pivot/persevere 决策点',
      },
    ],
  },
  {
    id: 5,
    name: '交付',
    icon: '🚀',
    description: '完善方案，准备展示',
    steps: [
      {
        id: '5-1',
        phase: 5,
        step: 1,
        title: '动手做起来',
        description: '开始搭建你的作品吧！遇到问题随时问我',
        aiRole: 'architect',
        outputType: 'text',
        promptHint: '提供实现建议和资源推荐，鼓励自主探索',
      },
      {
        id: '5-2',
        phase: 5,
        step: 2,
        title: '回头看看你的进展',
        description: '检查一下你做到了什么、学到了什么，接下来该怎么做？',
        aiRole: 'reviewer',
        outputType: 'text',
        promptHint: '帮学员建立创新核算：从第一个 MVP 数据开始，评估是否达到预期，决定 pivot/persevere',
      },
      {
        id: '5-3',
        phase: 5,
        step: 3,
        title: '准备你的展示',
        description: '怎么向大家介绍你的项目？准备你的故事',
        aiRole: 'reviewer',
        outputType: 'text',
        promptHint: '引导学员准备电梯演讲：问题→方案→影响',
      },
      {
        id: '5-4',
        phase: 5,
        step: 4,
        title: '最后检查一遍',
        description: '所有材料都准备好了吗？做最后一轮检查',
        aiRole: 'reviewer',
        outputType: 'list',
        promptHint: '逐项检查提交材料：方案描述、原型、展示材料等',
      },
    ],
  },
];

export function getPhase(phaseId: number): WorkflowPhase | undefined {
  return workflowPhases.find(p => p.id === phaseId);
}

export function getStep(phaseId: number, step: number) {
  const phase = getPhase(phaseId);
  return phase?.steps.find(s => s.step === step);
}

export function totalSteps(): number {
  return workflowPhases.reduce((acc, p) => acc + p.steps.length, 0);
}
